jobs:
  assign_one_project:
    env:
      COLUMN_NAME: Backlog
      MY_GITHUB_TOKEN: ${{ secrets.PROJECT_GITHUB_TOKEN }}
      QA_PROJECT_ID: 6
    name: Assign to QA Project
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: 'contains(github.event.issue.labels.*.name, ''Passed Internal QA'')

        '
      name: Assign issues with `Passed Internal QA` label to QA project
      uses: srggrs/assign-one-project-github-action@1.1.3
      with:
        column_name: ${{ env.COLUMN_NAME }}
        project: https://github.com/orgs/dotCMS/projects/${{ env.QA_PROJECT_ID }}
name: Assign issues with `Passed Internal QA` label to QA project
on:
  repository_dispatch:
    types: trigger-ga___assign-issues-to-qa-project.yml
