jobs:
  discover_tags:
    name: Discover DotCMS docker tags
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      if: env.DEBUG == 'true'
      name: GITHUB CONTEXT
      run: echo "$GITHUB_CONTEXT"
    - continue-on-error: true
      name: Checkout core
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set Common Vars
      run: 'pwd && ls -las

        BUILD_ID=$(basename "${{ github.ref }}")

        BUILD_HASH=$(git log -1 --pretty=%h)

        BUILD_HASH=${BUILD_HASH::7}

        eval $(cat dotCMS/gradle.properties| grep dotcmsReleaseVersion)

        DOTCMS_VERSION="${dotcmsReleaseVersion}"


        echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV

        echo "BUILD_HASH=${BUILD_HASH}" >> $GITHUB_ENV

        echo "DOTCMS_VERSION=${DOTCMS_VERSION}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      id: discover-docker-tags
      name: Discover docker tags
      uses: dotcms/discover-docker-tags-action@v2.0
      with:
        also_latest: ${{ github.event.inputs.also_latest }}
        hash: ${{ env.BUILD_HASH }}
        label: ${{ github.event.inputs.custom_label }}
        update_stable: ${{ github.event.inputs.updata_stable_tags }}
        version: ${{ ENV.DOTCMS_VERSION }}
name: discover-dotcms-docker-image
on:
  repository_dispatch:
    types: trigger-ga___discover-docker-tags.yml
