jobs:
  docker:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: ./.github/actions/cleanup-runner
    - continue-on-error: true
      id: meta
      name: Docker meta
      uses: docker/metadata-action@v4
      with:
        images: 'dotcms/dotcms-dev

          '
        tags: 'type=sha,enable=true,priority=100,prefix=master_,suffix=_SNAPSHOT,format=short

          type=raw,value=master_latest_SNAPSHOT

          '
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Login to Docker Hubdocker-build-master-branch.yml
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_TOKEN }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        build-args: 'DOTCMS_DOCKER_TAG=master_latest_SNAPSHOT

          '
        context: docker/dev-env
        no-cache: true
        platforms: linux/amd64,linux/arm64
        pull: true
        push: false
        tags: ${{ steps.meta.outputs.tags }}
name: Build/Push dotCMS Dev Image (nightly)
on:
  repository_dispatch:
    types: trigger-ga___docker-build-dev-image.yml
