jobs:
  label-issues:
    name: Label issues
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout core
      uses: actions/checkout@v4
    - continue-on-error: true
      id: fetch-next-release-issues
      name: Fetch issues
      uses: ./.github/actions/issue-fetcher
      with:
        fetch_operation: WITH_LABELS
        fetch_value: ${{ github.event.inputs.labels }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Apply label operation
      uses: ./.github/actions/issue-labeler
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issues_json: ${{ steps.fetch-next-release-issues.outputs.issues }}
        labels: ${{ github.event.inputs.applying_labels }}
        operation: ${{ github.event.inputs.operation }}
name: Label Issues
on:
  repository_dispatch:
    types: trigger-ga___label-issues.yml
