jobs:
  release-trigger:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: master
    - continue-on-error: true
      uses: ./.github/actions/cleanup-runner
    - continue-on-error: true
      id: create-release-branch
      name: Create Release Branch
      run: "git config user.name \"${{ secrets.CI_MACHINE_USER }}\"\ngit config user.email\
        \ \"dotCMS-Machine-User@dotcms.com\"\n\nRELEASE_VERSION=${{ github.event.inputs.release_version\
        \ }}\nRELEASE_TAG=\"v${RELEASE_VERSION}\"\nRELEASE_BRANCH=\"release-${RELEASE_VERSION}\"\
        \necho \"RELEASE_VERSION=${RELEASE_VERSION}\" >> $GITHUB_ENV\necho \"RELEASE_TAG=${RELEASE_TAG}\"\
        \ >> $GITHUB_ENV\necho \"RELEASE_BRANCH=${RELEASE_BRANCH}\" >> $GITHUB_ENV\n\
        \nif git rev-parse \"${RELEASE_TAG}\" >/dev/null 2>&1; then \n  echo \"Tag\
        \ ${RELEASE_TAG} exists, removing it\"\n  git push origin :refs/tags/${RELEASE_TAG}\n\
        fi\n\nremote=$(git ls-remote --heads https://github.com/dotCMS/core.git ${RELEASE_BRANCH}\
        \ | wc -l | tr -d '[:space:]')\n[[ \"${remote}\" == '1' ]] \\\n  && echo \"\
        Release branch ${RELEASE_BRANCH} already exists, removing it\" \\\n  && git\
        \ push origin :${RELEASE_BRANCH}\n\ngit reset --hard ${{ github.event.inputs.commit_hash\
        \ }}\ngit checkout -b ${RELEASE_BRANCH}\ngit push origin ${RELEASE_BRANCH}\n"
    - continue-on-error: true
      name: Modify gradle.properties
      run: 'sed -i ''s/dotcmsReleaseVersion=.*/dotcmsReleaseVersion=${{ env.RELEASE_VERSION
        }}/'' dotCMS/gradle.properties

        git commit -am "Update dotCmsReleaseVersion to ${{ env.RELEASE_VERSION }}"

        RELEASE_COMMIT=$(git log -1 --pretty=%H)

        echo "RELEASE_COMMIT: ${RELEASE_COMMIT}"

        git push origin ${{ env.RELEASE_BRANCH }}

        echo "RELEASE_COMMIT=${RELEASE_COMMIT}" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Create Release
      run: "curl -X POST \\\n  -H \"Accept: application/vnd.github+json\" \\\n  -H\
        \ \"X-GitHub-Api-Version: 2022-11-28\" \\\n  -H \"Authorization: Bearer ${{\
        \ secrets.GITHUB_TOKEN }}\" \\\n  https://api.github.com/repos/dotCMS/core/releases\
        \ \\\n  -d '{\"tag_name\": \"${{ env.RELEASE_TAG }}\", \"name\": \"Release\
        \ ${{ env.RELEASE_VERSION }}\", \"target_commitish\": \"${{ env.RELEASE_COMMIT\
        \ }}\", \"draft\": false, \"prerelease\": false, \"generate_release_notes\"\
        : false}'\n"
name: Release Trigger
on:
  repository_dispatch:
    types: trigger-ga___release-trigger.yml
