jobs:
  vulnerability-scan:
    continue-on-error: true
    env:
      DOT_CICD_BRANCH: master
      GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PULL_REQUEST: ${{ github.event.number }}
    name: Vulnerability Scan Automation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      if: env.DEBUG == 'true'
      name: GITHUB CONTEXT
      run: echo "$GITHUB_CONTEXT"
    - continue-on-error: true
      id: get-commit_message
      name: Get commit message
      uses: dotcms/get-commit_message@master
      with:
        accessToken: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Set Common Vars
      run: "if [[ \"${{ github.event_name }}\" == \"pull_request\" ]]; then\n  BUILD_ID=\"\
        ${{ github.head_ref }}\"\nelse\n  BUILD_ID=$(basename \"${{ github.ref }}\"\
        )\nfi\n\nCOMMIT_MESSG=\"${{ steps.get-commit_message.outputs.commit_message\
        \ }}\"\necho \"COMMIT_MESSG: ${COMMIT_MESSG}\"\nif [[ ${COMMIT_MESSG} =~ scan-dotcms\
        \ ]]; then\n  jobRun=true\nelse\n  jobRun=false\nfi\necho \"jobRun=${jobRun}\"\
        \ >> $GITHUB_ENV\necho \"BUILD_ID=${BUILD_ID}\" >> $GITHUB_ENV\nif [[ \"${{\
        \ matrix.scan }}\" == 'full' ]]; then\n  echo \"RESET_STARTER=true\" >> $GITHUB_ENV\n\
        fi\n"
    - continue-on-error: true
      if: env.jobRun == 'true'
      name: Prepare dot-cicd
      run: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/dotCMS/dot-cicd/${DOT_CICD_BRANCH}/seed/install-dot-cicd.sh)"

        '
    - continue-on-error: true
      env:
        CUSTOM_STARTER_URL: https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240213/starter-20240213.zip
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
      if: env.jobRun == 'true'
      name: Run Vulnerabily Scan
      run: '../dotcicd/library/pipeline.sh runSidecar scan ${{ matrix.scan }}

        '
    strategy:
      fail-fast: false
      matrix:
        scan:
        - api
        - baseline
        - full
name: vulnerability-scan-automation
on:
  repository_dispatch:
    types: trigger-ga___vulnerability-scan.yml
